version: "3.8"

services:
  backend:
    build: ./backend
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  websocket-server:
    build: ./backend
    command: python server.py
    ports:
      - "8765:8765"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app